server:
  port: 8001

spring:
  application:
    name: cloud-payment-8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud-2020?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.byl.springcloud.entities
#  当你需要使用mybatis-config.xml 配置文件的时候你就需要配置config-location，config-location的作用是确定mybatis-config.xml文件位置的，
#  而mapper-locations是用来注册你写的xxxmapper.xml文件。如果你使用了mybatis-config.xml，并且里面配置了mapper，那就不需要mapper-locations，
#  mapper-locations: classpath:mapper/*.xml
#  config-location: classpath:config/mybatis-config.xml
